/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * SCRUM-148: Static map of KOL doctor slugs → playlists they appear in.
 * Generated by frontend/scripts/generate-kol-playlists.mjs at 2026-08-18T23:13:22.590Z.
 * Source: https://devapp.communityhealth.media/api
 *
 * Regenerate when Marni publishes new playlists:
 *   node frontend/scripts/generate-kol-playlists.mjs
 *
 * 10 playlists total, 21 KOLs mapped, 24 playlist ↔ KOL edges.
 *
 * Static because WordPress + curator playlist plumbing is on the deprecation
 * path — Framer migration will replace this with proper collection references.
 */

export interface KolPlaylistRef {
  /** YouTube playlist ID (starts with PL...). */
  id: string;
  /** Full playlist title as shown on YouTube. */
  title: string;
  /** Thumbnail from YouTube's playlist snippet. */
  thumbnailUrl: string;
  /** Number of videos in the playlist. */
  videoCount: number;
}

/**
 * Keyed by MediaHub doctor slug (e.g. "bardia", "garrido-castro").
 * Same slug shape returned by GET /api/catalog/doctors.
 */
export const KOL_PLAYLISTS: Record<string, KolPlaylistRef[]> = {
  "bagegni": [
    {
      "id": "PL2Hl5AUWjkchqQepKWLujRJqTzWBq7ga3",
      "title": "Is HER2+ Metastatic Breast Cancer Curable? What Comes Next - Dr. Gregory Vidal & Dr. Nusayba Bagegni",
      "thumbnailUrl": "https://i.ytimg.com/vi/kNu0bwP1M-s/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "ballinger": [
    {
      "id": "PL2Hl5AUWjkcj4cuPQAXMyHtcPgcDRhWiq",
      "title": "Cleopatra, DESTINY-Breast09 & What Comes Next with Drs. Bill Gradishar, Tarah Ballinger, & Megan Kruse",
      "thumbnailUrl": "https://i.ytimg.com/vi/iqQ6z4nzvyE/hqdefault.jpg",
      "videoCount": 7
    }
  ],
  "bardia": [
    {
      "id": "PL2Hl5AUWjkci_7ihXb_CxYRx44m5advu4",
      "title": "DESTINY-Breast09 & the Future of Care with Drs. Irene Kang & Aditya Bardia",
      "thumbnailUrl": "https://i.ytimg.com/vi/V2zrRyH7Bfk/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "dietrich": [
    {
      "id": "PL2Hl5AUWjkchY4CKaO-YFbzZ85bmIrDLA",
      "title": "Has HER2+ First-Line Treatment Officially Changed? with Drs. Neil Iyengar & Martin Dietrich",
      "thumbnailUrl": "https://i.ytimg.com/vi/PTPrAKSxar0/hqdefault.jpg",
      "videoCount": 7
    }
  ],
  "gradishar": [
    {
      "id": "PL2Hl5AUWjkcj4cuPQAXMyHtcPgcDRhWiq",
      "title": "Cleopatra, DESTINY-Breast09 & What Comes Next with Drs. Bill Gradishar, Tarah Ballinger, & Megan Kruse",
      "thumbnailUrl": "https://i.ytimg.com/vi/iqQ6z4nzvyE/hqdefault.jpg",
      "videoCount": 7
    },
    {
      "id": "PL2Hl5AUWjkch8F7LYwrK7ZSkeuIu1uZ1v",
      "title": "Datopotamab Deruxtecan vs Sacituzumab Govitecan Explained with Drs. Bill Gradishar & Tiffany Traina",
      "thumbnailUrl": "https://i.ytimg.com/vi/Oih_DvEh4FI/hqdefault.jpg",
      "videoCount": 5
    }
  ],
  "iyengar": [
    {
      "id": "PL2Hl5AUWjkchY4CKaO-YFbzZ85bmIrDLA",
      "title": "Has HER2+ First-Line Treatment Officially Changed? with Drs. Neil Iyengar & Martin Dietrich",
      "thumbnailUrl": "https://i.ytimg.com/vi/PTPrAKSxar0/hqdefault.jpg",
      "videoCount": 7
    },
    {
      "id": "PL2Hl5AUWjkcgctNi0rmnc_UcGhfgVBQ5w",
      "title": "Is T-DXd + Pertuzumab New First Line Standard with Drs. Neil Iyengar, Komal Jhaveri, & Igor Makhlin",
      "thumbnailUrl": "https://i.ytimg.com/vi/6IBpBFfMV5Q/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "jhaveri": [
    {
      "id": "PL2Hl5AUWjkcgctNi0rmnc_UcGhfgVBQ5w",
      "title": "Is T-DXd + Pertuzumab New First Line Standard with Drs. Neil Iyengar, Komal Jhaveri, & Igor Makhlin",
      "thumbnailUrl": "https://i.ytimg.com/vi/6IBpBFfMV5Q/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "kang": [
    {
      "id": "PL2Hl5AUWjkci_7ihXb_CxYRx44m5advu4",
      "title": "DESTINY-Breast09 & the Future of Care with Drs. Irene Kang & Aditya Bardia",
      "thumbnailUrl": "https://i.ytimg.com/vi/V2zrRyH7Bfk/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "krie": [
    {
      "id": "PL2Hl5AUWjkcj1AMFtfkKNxWru-8oqXiE_",
      "title": "DB09 Leading Towards New FirstLine Standard Of Care with Drs. Amy Krie, Mabel Mardones, & Anne O'Dea",
      "thumbnailUrl": "https://i.ytimg.com/vi/H_njEcRMEMg/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "kruse": [
    {
      "id": "PL2Hl5AUWjkcj4cuPQAXMyHtcPgcDRhWiq",
      "title": "Cleopatra, DESTINY-Breast09 & What Comes Next with Drs. Bill Gradishar, Tarah Ballinger, & Megan Kruse",
      "thumbnailUrl": "https://i.ytimg.com/vi/iqQ6z4nzvyE/hqdefault.jpg",
      "videoCount": 7
    }
  ],
  "makhlin": [
    {
      "id": "PL2Hl5AUWjkcgctNi0rmnc_UcGhfgVBQ5w",
      "title": "Is T-DXd + Pertuzumab New First Line Standard with Drs. Neil Iyengar, Komal Jhaveri, & Igor Makhlin",
      "thumbnailUrl": "https://i.ytimg.com/vi/6IBpBFfMV5Q/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "mardones": [
    {
      "id": "PL2Hl5AUWjkcj1AMFtfkKNxWru-8oqXiE_",
      "title": "DB09 Leading Towards New FirstLine Standard Of Care with Drs. Amy Krie, Mabel Mardones, & Anne O'Dea",
      "thumbnailUrl": "https://i.ytimg.com/vi/H_njEcRMEMg/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "mouabbi": [
    {
      "id": "PL2Hl5AUWjkchaSnGOSPayrLvVI5VZw-Xr",
      "title": "Rethinking 1L HER2+ Therapy + T-DXd with Drs. Jason Mouabbi, Joyce O’Shaughnessy & Mothaffar Rimawi",
      "thumbnailUrl": "https://i.ytimg.com/vi/vdnpqhH7Src/hqdefault.jpg",
      "videoCount": 6
    }
  ],
  "odea": [
    {
      "id": "PL2Hl5AUWjkcj1AMFtfkKNxWru-8oqXiE_",
      "title": "DB09 Leading Towards New FirstLine Standard Of Care with Drs. Amy Krie, Mabel Mardones, & Anne O'Dea",
      "thumbnailUrl": "https://i.ytimg.com/vi/H_njEcRMEMg/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "oshaughnessy": [
    {
      "id": "PL2Hl5AUWjkchaSnGOSPayrLvVI5VZw-Xr",
      "title": "Rethinking 1L HER2+ Therapy + T-DXd with Drs. Jason Mouabbi, Joyce O’Shaughnessy & Mothaffar Rimawi",
      "thumbnailUrl": "https://i.ytimg.com/vi/vdnpqhH7Src/hqdefault.jpg",
      "videoCount": 6
    }
  ],
  "pegram": [
    {
      "id": "PL2Hl5AUWjkcgiwYUMn1xZE0OcJ7kkFgC_",
      "title": "Is T-DXd Rewriting First-Line HER2+ Metastatic Breast Cancer with Drs. Mark Pegram & Fengting Yan",
      "thumbnailUrl": "https://i.ytimg.com/vi/R_0Ual-cd2E/hqdefault.jpg",
      "videoCount": 6
    },
    {
      "id": "PL2Hl5AUWjkch0BhbecHExDoFI-BIOCuvp",
      "title": "New First-Line Strategies in HER2+ Metastatic Breast Cancer with Dr. Mark Pegram & Dr. Carol Tweed",
      "thumbnailUrl": "https://i.ytimg.com/vi/Zhq16QVNcFE/hqdefault.jpg",
      "videoCount": 6
    }
  ],
  "rimawi": [
    {
      "id": "PL2Hl5AUWjkchaSnGOSPayrLvVI5VZw-Xr",
      "title": "Rethinking 1L HER2+ Therapy + T-DXd with Drs. Jason Mouabbi, Joyce O’Shaughnessy & Mothaffar Rimawi",
      "thumbnailUrl": "https://i.ytimg.com/vi/vdnpqhH7Src/hqdefault.jpg",
      "videoCount": 6
    }
  ],
  "traina": [
    {
      "id": "PL2Hl5AUWjkch8F7LYwrK7ZSkeuIu1uZ1v",
      "title": "Datopotamab Deruxtecan vs Sacituzumab Govitecan Explained with Drs. Bill Gradishar & Tiffany Traina",
      "thumbnailUrl": "https://i.ytimg.com/vi/Oih_DvEh4FI/hqdefault.jpg",
      "videoCount": 5
    }
  ],
  "tweed": [
    {
      "id": "PL2Hl5AUWjkch0BhbecHExDoFI-BIOCuvp",
      "title": "New First-Line Strategies in HER2+ Metastatic Breast Cancer with Dr. Mark Pegram & Dr. Carol Tweed",
      "thumbnailUrl": "https://i.ytimg.com/vi/Zhq16QVNcFE/hqdefault.jpg",
      "videoCount": 6
    }
  ],
  "vidal": [
    {
      "id": "PL2Hl5AUWjkchqQepKWLujRJqTzWBq7ga3",
      "title": "Is HER2+ Metastatic Breast Cancer Curable? What Comes Next - Dr. Gregory Vidal & Dr. Nusayba Bagegni",
      "thumbnailUrl": "https://i.ytimg.com/vi/kNu0bwP1M-s/hqdefault.jpg",
      "videoCount": 9
    }
  ],
  "yan": [
    {
      "id": "PL2Hl5AUWjkcgiwYUMn1xZE0OcJ7kkFgC_",
      "title": "Is T-DXd Rewriting First-Line HER2+ Metastatic Breast Cancer with Drs. Mark Pegram & Fengting Yan",
      "thumbnailUrl": "https://i.ytimg.com/vi/R_0Ual-cd2E/hqdefault.jpg",
      "videoCount": 6
    }
  ]
};

/**
 * Reverse index: playlist id → list of doctor slugs featured in it.
 * Used by /catalog/playlist/:id to render "Featured physicians" strip.
 */
export const PLAYLIST_KOLS: Record<string, string[]> = {
  "PL2Hl5AUWjkcgctNi0rmnc_UcGhfgVBQ5w": [
    "iyengar",
    "jhaveri",
    "makhlin"
  ],
  "PL2Hl5AUWjkcgiwYUMn1xZE0OcJ7kkFgC_": [
    "pegram",
    "yan"
  ],
  "PL2Hl5AUWjkch0BhbecHExDoFI-BIOCuvp": [
    "pegram",
    "tweed"
  ],
  "PL2Hl5AUWjkch8F7LYwrK7ZSkeuIu1uZ1v": [
    "gradishar",
    "traina"
  ],
  "PL2Hl5AUWjkchY4CKaO-YFbzZ85bmIrDLA": [
    "dietrich",
    "iyengar"
  ],
  "PL2Hl5AUWjkchaSnGOSPayrLvVI5VZw-Xr": [
    "mouabbi",
    "oshaughnessy",
    "rimawi"
  ],
  "PL2Hl5AUWjkchqQepKWLujRJqTzWBq7ga3": [
    "bagegni",
    "vidal"
  ],
  "PL2Hl5AUWjkci_7ihXb_CxYRx44m5advu4": [
    "bardia",
    "kang"
  ],
  "PL2Hl5AUWjkcj1AMFtfkKNxWru-8oqXiE_": [
    "krie",
    "mardones",
    "odea"
  ],
  "PL2Hl5AUWjkcj4cuPQAXMyHtcPgcDRhWiq": [
    "ballinger",
    "gradishar",
    "kruse"
  ]
};
